@startuml
start
repeat
:ingresar correo electronico;
if (validar formato) then (true)
    :ingresar contraseña;
    if (validar formato) then (true)
        :click en boton iniciar sesion;
        :Enviar formulario;
        if  (Validar credenciales) then (true)
            :redireccionar a pagina principal;
            end
            note
                caso de exito
            end note
        else (false)
            :mostrar mensaje de error;
        endif
    else (false)
        :Mostar mensaje de error;
    endif
else (false)
    :Mostar mensaje de error;
endif
repeat while ()
stop

@enduml
